build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - tests/*
    - vendor/*
